### PR TITLE
Term proposal

### PR DESCRIPTION
**Pull request by alishsuper**

### CODE REVIEW

**Comment by yungyuc** [comment]
Please remove the file in `term_proposal/` and leave only the one in your sub-directory.

**Comment by yungyuc** [comment]
And, please make the PR to be against the branch `term-proposal`, not `master`.

**Comment by alishsuper** [comment]
It's done. I'm sorry for that. In the future I will try to be more careful

**Comment by yungyuc** [comment]
You now touch hw2 files and and readme.  You shouldn't do that.  Please correct.

And you are using too many commits for adding one file (in your sub-directory).  When you correct the mistakes, please squash the multiple commits into one with this PR.

You don't need to apologize.  I am guessing you are not familiar with using git for collaborative work.  In this case it's normal to make mistakes.  It's good for you to try, mistake, and correct.  It's the only way that I know to sharpen your engineering skills.

**Comment by alishsuper** [comment]
I've tried to combine all commits but I got this error with conflicting files. I can resolve conflicts but then github asks me to merge this. So I just left it. I hope you will help me solve this problem with github. Thanks!

**Pull request closed without merging**
