### PR TITLE
hw2 0845029

### PR DESCRIPTION
**Pull request by yarinbar**

### CODE REVIEW

**Comment by tigercosmos** [comment]
@yarinbar you should not and never upload binary files to the repository.

**Comment by tigercosmos** [comment]
use `.gitignore` to help you

**Comment by tigercosmos** [comment]
@yarinbar  you should only have files relevant to HW2 in this PR.
To do that, you should work on a different branch other than the `master` branch.

BTW, I see you have `multiply.cpython-37m-x86_64-linux-gnu.so` in HW3. As I mentioned, it is not allowed to do that, since you can see it is almost `1.3MB`, which is an overload for others to clone the repo.

**Comment by yarinbar** [comment]
new PR without unrelated stuff -
https://github.com/yungyuc/nsdhw_19au/pull/48

**Pull request merged**
