### PR TITLE
Titaneric hw3

### PR DESCRIPTION
**Pull request by titaneric**

### CODE REVIEW

**Comment by tigercosmos** [comment]
../validate.py
set PRELOAD_MKL if you see (Linux) MKL linking error
rm -rf *.so
g++ -Wl,--no-as-needed -std=c++17 -O3 -g -m64  -shared -Wall -fPIC -I/home/ubuntu/opt/conda/include `python3 -m pybind11 --includes` -o _matrix`python3-config --extension-suffix` matrix.cpp /home/ubuntu/opt/conda/lib/libmkl_intel_lp64.so /home/ubuntu/opt/conda/lib/libmkl_sequential.so /home/ubuntu/opt/conda/lib/libmkl_core.so -lpthread -lm -ldl
export PRELOAD_MKL=True
python3 matrix_test.py
INTEL MKL ERROR: /home/ubuntu/opt/conda/lib/libmkl_avx2.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
Makefile:45: recipe for target 'test' failed
make: *** [test] Error 2
*** validation failed

@titaneric

**Comment by titaneric** [comment]
Hi @tigercosmos TA,

I would like to know whether you set the PRELOAD_MKL or not during the validation?

**Comment by tigercosmos** [comment]
no  I thought it should be in makefile?

**Comment by titaneric** [comment]
Hi,
the lecturer had updated the validation process, as the following said

> The grader may attempt to run the above commands with the environment variable PRELOAD_MKL set, if validate.py doesn't pass without it. Your work is considered pass in either case.

from [hw3](https://github.com/yungyuc/nsdhw_19au/tree/hw3/hw3)

Please validate my assignment with PRELOAD_MKL=True, thanks in advance.

**Comment by tigercosmos** [comment]
I just missed it. thanks

**Pull request merged**
