### PR TITLE
Hw6 Yarinbar 0845029

### PR DESCRIPTION
**Pull request by yarinbar**

### CODE REVIEW

**Comment by tigercosmos** [comment]
@yarinbar you delete files not relevant to HW6 in commits.

**Comment by yarinbar** [comment]
i deleted them because that it didnt let you automatically merge

**Comment by tigercosmos** [comment]
there are many commits in your PR, which are not yours.
The easy way is to pull the latest `hw6` branch code, and commit the code based on the latest commit.
You can also do it by `git rebase`  command, but it is more complicated.

**Comment by yarinbar** [comment]
with all the other students' code?
but how can i create a branch without the previous commits?

did you mean 'clone' the latest hw6 branch?

**Comment by tigercosmos** [comment]
the easiest way I can think about:

```
git clone this_repo
cd nsdhw_19au
git add remote yarinbar your_forked_repo.git

git fetch
git checkout hw6
# modify and commit based on latest hw6 in this repo
git push -u yarinbar hw6-2 #push to your repo
# pull request hw6-2 to hw6
```

**Pull request closed without merging**
